import "./globals.css";
import { Montserrat, Noto_Serif } from 'next/font/google';
import FaleConosco from "@/components/faleConosco.jsx";
import BackgroundHome from "@/components/background.jsx";   
import Rodape from "@/components/rodape.jsx";
import Navbar from "@/components/navbar";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

const notoSerif = Noto_Serif({
  subsets: ['latin'],
  variable: '--font-noto-serif',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${notoSerif.variable} h-full antialiased`}
    >
      <body className="font-sans">
        <div className="bg-[#320A27] min-h-screen flex flex-col">

          <div className="flex-1">
          <Navbar />

            {children}

            <div className="mt-20">
              <FaleConosco id="contato"/>
            </div>

            <div className=" mb-[150px]">
              <Rodape />
            </div>
          </div>


        </div>
      </body>
    </html>
  );
}
